[Review] 4주차 코드 리뷰 PR
kakao-tech-campus-2nd-step3/Team5_FE pull request #18
Opened 2024-09-26 12:51 UTC by hyunaeri

## 🔧 작업 내용

- 4주차 코드 리뷰 요청입니다.
- 공용 컴포넌트 구현 #14  
- 라우터 설정 #12 

<br>

## 📌 참고 사항

- 이번 4주차는 프로젝트 전반에서 공통으로 쓰일 컴포넌트들을 구현 했습니다.
- img, input, textarea, AsyncBoundary, select, spinner, loadingview
- 위에서 구현한 AsyncBoundary 를 적용하여 라우터를 설정 했습니다.

<br>

## ❗️ 현재 버그
X

<br>

## ✓ Git close
X

2024-10-06 04:08 UTC, minsekim1 commented on components.json
> +    "css": "src/index.css",
"css": "src/index.css"는 Tailwind CSS의 설정을 지정한 것으로, 이 경로에 해당하는 파일이 존재해야 올바르게 Tailwind 스타일을 적용할 수 있습니다.

현재는 아직 파일이 없는것 같네요.
아직 설정중인것으로 보이므로 가볍게 체크만 해주시면 좋을 것 같아요.
참고 가이드: [링크](https://velog.io/@dmk-jongwho/Tailwind-CSS-%EC%A0%81%EC%9A%A9%EA%B8%B01%ED%8E%B8-%EC%84%A4%EC%B9%98-%EC%82%AC%EC%9A%A9)

2024-10-06 04:11 UTC, minsekim1 commented on package.json
>      "build-storybook": "storybook build"
[옵션] 
scripts에 type-check 추가:

"type-check": "tsc --noEmit"와 같은 스크립트를 추가하여 TypeScript 타입 검사를 별도로 실행하는 것이 좋습니다. 이는 CI/CD 파이프라인에 추가해 타입 오류를 미리 검출하는 데 유용합니다.

2024-10-06 04:12 UTC, minsekim1 commented on package.json
>      "build-storybook": "storybook build"
[옵션] 
ESLint 및 Prettier 통합:

이미 "eslint-plugin-prettier"를 사용하고 있으므로, "lint" 스크립트에 "prettier --check"를 추가하여 코드 스타일을 정리하고 일관성을 유지할 수 있습니다. "lint": "eslint . && prettier --check ."와 같이 설정할 수 있습니다.

2024-10-06 04:16 UTC, minsekim1 commented on src/assets/Logo.png
public에 넣어도 상관없는 파일(외부에 공개되어도 되는 파일)은 puclic/assets 에 넣으면 좋습니다.

(상세 설명)
src/assets/Logo.png 파일이 애플리케이션 로고와 같이 외부에 공개되어도 문제가 없는 정적 자산이라면, public/assets 폴더로 이동시키는 것이 좋습니다. 이렇게 하면 빌드 프로세스에서 해당 파일이 그대로 복사되어 public 폴더에 남아있고, 웹 서버에서 직접 접근할 수 있도록 관리할 수 있습니다.

추가적으로, public 폴더에 있는 파일들은 URL을 통해 쉽게 접근할 수 있기 때문에, 공개 가능한 파일이라면 이러한 접근 방식이 유리할 수 있습니다. 예를 들어, <img src="/assets/Logo.png" />와 같이 HTML에서 쉽게 참조할 수 있어 편리합니다.

이러한 접근 방식은 빌드 도구에서 파일을 번들링하거나 압축하는 과정을 거치지 않기 때문에, 사용자가 자주 접근하는 정적 자산에 대해 성능상의 이점을 제공할 수도 있습니다.

2024-10-06 04:28 UTC, minsekim1 commented on src/components/common/AsyncBoundary/index.tsx
> +      <ErrorBoundary ref={ref} fallback={rejectedFallback ?? <></>}>
ErrorBoundary에 대해서 console.log를 통해서 에러 핸들링을 개선할 수 있습니다.
```
<ErrorBoundary
  ref={ref}
  fallback={rejectedFallback ?? defaultErrorFallback}
  **onReset={() => console.log('Error boundary reset')}
  onError={(error, info) => console.error('Caught an error:', error, info)}**
>
  <Suspense fallback={pendingFallback ?? defaultPendingFallback}>
    {children}
  </Suspense>
</ErrorBoundary>
```

2024-10-06 04:41 UTC, minsekim1 commented on src/components/common/view/LoadingView.tsx
> +  height: 100vh;
width와 height 설정
- width: 100%; height: 100vh;로 설정되어 화면 전체를 차지하게 하고 있습니다. 이 설정은 페이지 전체가 로딩 상태일 때 적절하지만, 이 컴포넌트가 특정 섹션이나 컨테이너 안에서 사용될 경우 오버레이가 되면서 레이아웃 문제를 야기할 수 있습니다.
- 만약 LoadingView가 섹션 단위에서도 사용될 가능성이 있다면 height를 유연하게 설정하는 것이 좋습니다. 예를 들어, height: 100%;로 설정하고 부모의 높이에 맞게 대응하게끔 조정할 수 있습니다.

2024-10-06 04:43 UTC, minsekim1 commented on src/components/common/view/LoadingView.tsx
> +  padding: 80px 16px;
이 부분도 마찬가지로 섹션 단위 (전체화면이 아닌 탭 내부 등 다양한 곳)에 활용할 예정이라면 padding: 80px 16px; 보다는 % 와 min max 활용해서 넣으면 좋을 것 같습니다.

2024-10-06 04:50 UTC, minsekim1 commented on src/router/Router.tsx
페이지 컴포넌트 코드 분리
- 페이지에 lazy 로딩(참고 [링크](https://velog.io/@nearworld/React-lazy-%ED%95%A8%EC%88%98)) 을 넣으면 좋을 것 같습니다.
- 현재 routesConfig에서 각 페이지 컴포넌트를 element로 직접 지정하고 있습니다. 라우팅 설정과 컴포넌트의 의존성을 느슨하게 하기 위해 Lazy Loading을 사용하는 것이 좋습니다.
- 이를 통해 페이지 단위에서 코드 분할을 할 수 있고, 최초 로딩 시간을 줄여 성능 최적화가 가능합니다.
예시:
```
import React, { lazy } from 'react';

const RootPage = lazy(() => import('@/pages/RootPage'));
const MainPage = lazy(() => import('@/pages/main/index'));

const routesConfig: AppRouteObject[] = [
  {
    path: '/',
    element: (
      <React.Suspense fallback={<LoadingView />}>
        <RootPage />
      </React.Suspense>
    ),
    id: 'root',
    errorElement: <ErrorPage />,
    children: [
      { 
        index: true, 
        element: (
          <React.Suspense fallback={<LoadingView />}>
            <MainPage />
          </React.Suspense>
        ) 
      },
    ],
  },
];
```

2024-10-06 04:53 UTC, minsekim1 requested changes
로딩 컴포넌트, 헤더 컴포넌트와 공통 css 처리에 대해서 잘 보았습니다.
개별 라우팅을 처리하기보다 공통으로 묶어 처리하면 더 간단하게 해결 가능해서 코멘트 달아놨어요.

추가로 사용하지 않는 index.html도 삭제하면 좋을 것 같아요.

2024-10-07 07:12 UTC, KimKyuHoi commented on src/components/common/view/LoadingView.tsx
> +  padding: 80px 16px;
이 경우 제가 Spinner로 따로 컴포넌트를 구현했기 때문에 Spinner컴포넌트로 탭 내부 등 다양한 곳에 활용할 예정입니다 :)

2024-10-18 10:53 UTC, closed without merging