[Review] 7주차 코드 리뷰 PR
kakao-tech-campus-2nd-step3/Team5_FE pull request #42
Opened 2024-10-18 11:07 UTC by hyunaeri

## 🔧 작업 내용

- #35 
- #37 
- #39 

<br>

## 📌 참고 사항
> _`pnpm run dev` 를 통해 프로젝트를 실행하실 수 있습니다._

- 지난번 피드백 해주신 부분들을 모두 체크 했습니다!
- Merge 를 하지 않아서, 지난 주차 커밋들도 모두 쌓여버렸습니다. ㅠㅠ 기존의 PR 은 Close 처리 하였습니다.
- 지난번에 말씀드린 6주차 코드 리뷰 같은 경우 `Create week6 branch based on Master (c423ead)` 부터 봐주시면 감사하겠습니다!
- 이번 7주차 코드 리뷰의 경우 `Feat: Path 모듈화 시키기 (7a79ea3)` 부터 입니다!

<br>

## ※ 페이지 경로

- `/` 메인 페이지
- `/auto` 쇼츠 자동화 페이지
- `/myPage` 내 정보 수정 페이지 (마이 페이지)

<br>

## ⭐️ 핵심 기능 요약

- 프로젝트 전반적인 `코드 모듈화`
- `zod` 를 이용한 Form Validation 구현
- `Framer-motion` 을 이용한 애니메이션 구현

2024-10-20 00:09 UTC, minsekim1 commented on src/components/common/avatar/index.stories.tsx
> +      <AvatarImage src='' alt='User Avatar' />
이미지를 표시하지 못했을떄도 실패 이미지가 있으면 더 좋을 것 같아요

2024-10-20 00:20 UTC, minsekim1 commented on src/pages/ErrorPage.tsx
> +  return (
실 서비스라고 가정했을떄
```
useEffect(()=>{
    alert("접근할 수 없는 페이지입니다.");
    window.location.href = "/";
},[])
return null
```
이런식으로 강제 redirect시켜주면 좋아요.
또는 return null 대신에 이전으로 돌아가기 / 홈으로 돌아가기 버튼으로 만드셔도 유저의 입장에서 문제가 생겼을때 어떻게 해야하지? 에 대한 답변이 될 수 있을 거에요.

2024-10-20 00:28 UTC, minsekim1 requested changes
수고하셨습니다!
이번주는 페이지 몇개를 구현하셨는데 기존에 만든 컴포넌트, 또는 외부의 useForm 같은 Hook 을 잘 이용하고 계시다는 생각이 듭니다. 

개인적으로 css 스타일 같은 경우에 cn 이랑 style-compontent 두개로 구현하고 계시는데 분리하여 사용하는 기준이 있는지가 궁금합니다.

그외에 일부 수정 사항을 제외하면 완성도있는 코드라고 생각이 되네요. 페이지/컴포넌트는 계속해서 이런식으로 코드로 구현하고 백엔드랑 API 호환만 잘하면 큰 문제가 없을 것이라 생각해요.

마지막으로 디자인을 보고 페이지를 만들때마다 어떻게 백엔드 API를 반영할지에 대해서 가능하면 페이지 단위, 또는 작업단위(예: 로그인기능) 별로 어떤 데이터를 어디 페이지에서 받아서 localStorage / sessionstorage / cookie 등 어디에 담을지를 미리 정리해보면 두번 작업하지 않아서 시간도 줄고 불필요한 로직도 뺼 수 있어서 유용합니다!

2024-10-21 03:36 UTC, KimKyuHoi commented
> 수고하셨습니다! 이번주는 페이지 몇개를 구현하셨는데 기존에 만든 컴포넌트, 또는 외부의 useForm 같은 Hook 을 잘 이용하고 계시다는 생각이 듭니다.
> 
> 개인적으로 css 스타일 같은 경우에 cn 이랑 style-compontent 두개로 구현하고 계시는데 분리하여 사용하는 기준이 있는지가 궁금합니다.
> 
> 그외에 일부 수정 사항을 제외하면 완성도있는 코드라고 생각이 되네요. 페이지/컴포넌트는 계속해서 이런식으로 코드로 구현하고 백엔드랑 API 호환만 잘하면 큰 문제가 없을 것이라 생각해요.
> 
> 마지막으로 디자인을 보고 페이지를 만들때마다 어떻게 백엔드 API를 반영할지에 대해서 가능하면 페이지 단위, 또는 작업단위(예: 로그인기능) 별로 어떤 데이터를 어디 페이지에서 받아서 localStorage / sessionstorage / cookie 등 어디에 담을지를 미리 정리해보면 두번 작업하지 않아서 시간도 줄고 불필요한 로직도 뺼 수 있어서 유용합니다!

2024-11-01 08:35 UTC, merged